name: ${project.artifactId}
author: OffLuffy
description: ${project.description}
api-version: 1.13
version: ${project.version}
main: ${project.groupId}.${project.name}.${project.name}
softdepend: [Essentials]
commands:
  smoothsleepreload:
    description: Reloads SmoothSleep's config values
    permission: "smoothsleep.reload"
    usage: /ssreload
    aliases: [ssreload, ssleepreload, sleepreload]
  smoothsleeptoggle:
    description: Disables or enables the plugin. It will enable itself after a relaod/restart.
    permission: "smoothsleep.toggle"
    usage: /sstoggle
    aliases: [sstoggle, ssleeptoggle, sleeptoggle]
  smoothsleepmetrics:
    description: Toggles metrics for SmoothSleep
    permission: "smoothsleep.metrics"
    usage: /ssmetrics
    aliases: [ssmetrics, ssleepmetrics, sleepmetrics]
  smoothsleepaddworld:
    description: Adds a new world to the config
    permission: "smoothsleep.addworld"
    usage: /ssaddworld <world>
    aliases: [ssaddworld, ssleepaddworld, sleepaddworld]
  smoothsleepconfigureworld:
    description: Configure a world's SmoothSleep settings
    permission: "smoothsleep.configure"
    usage: /ssconf <world> <setting> <value>
    aliases: [ssconfigure, ssconf, ssleepconfigure, ssleepconf, sleepconfigure, sleepconf]
permission:
  smoothsleep.reload:
    description: Allows reloading SmoothSleep config
    default: op
  smoothsleep.toggle:
    description: Allows toggling SmoothSleep on/off
    default: op
  smoothsleep.ignore:
    description: Allows not needing to sleep
    default: op
  smoothsleep.metrics:
    description: Allows toggline metrics for SmoothSleep on/off
    default: op
  smoothsleep.addworld:
    description: Allows you to add new Worlds to the config with the /ssaddworld command
    default: op
  smoothsleep.configure:
    description: Allows you to modify a World's config settings with the /ssconf command
    default: op